Assets for AI/ML Profiling session
argonne-lcf/ALCF_Hands_on_HPC_Workshop pull request #54
Opened 2024-10-30 21:35 UTC by khossain4337

This pull request contains the PyTorch example, job submission scripts, and sample profiles for the AI/ML profiling session.

2024-10-30 22:02 UTC, felker requested changes
I agree with @nscottnichols comment about the binary profiles. You might want to move them to a public Box folder that you can share with attendees, in case they have issues generating the profiles.

2024-10-30 22:02 UTC, felker commented on ai_ml_profiling/README.md
> +
Follow these links to install a version of NVIDIA's Nsight Systems and Nsight Compute on your local machine.

2024-10-30 22:10 UTC, khossain4337 commented on ai_ml_profiling/README.md
> +A request to an user would be to try and run the run the scripts both from an interactive session and a batch submission *before* jumping on to using the profilers!
It should be either! Fixing it!

2024-10-30 22:11 UTC, khossain4337 commented on ai_ml_profiling/README.md
> +In the hands on session we will try to profile a simple PyTorch example. This mini-application (mini-benchmark) mimics the sequence parallelism strategy that we use for our auroraGPT training. Very s
Adding this.

2024-10-31 02:18 UTC, felker requested changes

2024-10-31 02:18 UTC, felker commented on ai_ml_profiling/README.md
> +In the hands on session we will try to profile a simple PyTorch example. This mini-application (mini-benchmark) mimics the sequence parallelism strategy that we use for our auroraGPT training. A simi
```suggestion
In the hands-on session we will try to profile a simple PyTorch example. This mini-application (or "mini-benchmark") mimics the sequence parallelism strategy that we use for our AuroraGPT training. A similar strategy is adopted by [Megatron-DeepSpeed](https://github.com/microsoft/Megatron-DeepSpeed) as well. 
```

2024-10-31 02:18 UTC, felker commented on ai_ml_profiling/README.md
> +    The `PROF_DIR` path is unused in this piece of code, as we have a separate script for launching the profiler.
why not delete this line from the script, then?

2024-10-31 02:18 UTC, felker commented on ai_ml_profiling/qsub_profile_polaris_sequence_parallelism.sh
> +mpiexec -n ${NRANKS} -ppn ${NRANKS_PER_NODE} --env TMPDIR=/eagle/datascience/hossainm/nsys_profile/tmpdir/ --cpu-bind=numa -l --line-buffer \
move TMPDIR to above, line after PROF_DIR, etc.

2024-10-31 02:18 UTC, felker commented on ai_ml_profiling/qsub_profile_polaris_sequence_parallelism.sh
> +WORK_DIR=/home/hossainm/hpc_workshop_october_2024
I would suggest removing your username the RHS of the environment variables, and make it clearer that the user needs to fill that in. For example:

```suggestion
WORK_DIR=[INSERT PATH IN HOME DIR]
```
or
```suggestion
WORK_DIR=/home/[USERNAME]/hpc_workshop_october_2024
```


Same with the above PBS options with paths

2024-10-31 02:18 UTC, felker commented on ai_ml_profiling/README.md
> +    Keeping track of the stdout (`.OU`) and the stderror (`.ER`) files are important, as we plan to ask the NVIDIA Nsight Systems profiler to print out a summary for us. This summary comes in the .OU
```suggestion
    Keeping track of the stdout (`.OU`) and the stderror (`.ER`) files are important, as we plan to ask the NVIDIA Nsight Systems profiler to print out a summary for us. This summary comes in the `.OU` file.
```

2024-10-31 02:18 UTC, felker commented on ai_ml_profiling/README.md
> +A request to an user would be to try and run the run the scripts either from an interactive session or a batch submission *before* jumping on to using the profilers!
```suggestion
Users should first attempt to run the following workload scripts without profiling on a Polaris compute node (from either an interactive session or a batch job submission).
```

2024-10-31 02:18 UTC, felker commented on ai_ml_profiling/README.md
> +[Download Nsight Compute](https://developer.nvidia.com/tools-overview/nsight-compute/get-started)
Would be nice to add a short section about `## View profiles` with some guiding hints on what to look for, what parameters you modify (unless you have that content planned for slides, etc.) Could also add a link to a public Box folder containing the `qdrep` etc. binary profile data for folks who are unable to collect the performance profiles themselves, for whatever reason.

2024-10-31 13:38 UTC, merged